/*
LICENCIA JOSE JAVIER BO
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
Lista de paquetes:
 */
package ud1_ejer6.gui.ventanas;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import ud1_ejer6.dto.Hijo;
import ud1_ejer6.gui.dialogos.D_AddHijo;
import ud1_ejer6.gui.dialogos.D_Error;
import ud1_ejer6.gui.dialogos.D_Exito;
import ud1_ejer6.logica.Logica;

/**
 *
 * @author Jose Javier BO
 */
public class Vregistro extends javax.swing.JFrame {

    /**
     * Creates new form Vregistro
     */
    public Vregistro() {
        initComponents();
        refrescarTabla();
        ocultarTabla();
        
    }
    
    
    
        /**
     *  MODIFICADO!
     *  Método privado de refresco de la tabla
     *  - Se puede configurar desde el diseño, pero es mejor desde código, 
     *    ya que posteriormente vamos a necesitar editarla.                  
    */
    private void refrescarTabla(){
 
        //1- Creación del modelo de tabla
        DefaultTableModel dtm = new DefaultTableModel();
        
        //2- Creo del índice de las columnas en el modelo
        String [] columnas = new String []{"Nombre","Apellidos", "Fecha Nac.", "Deporte", "Nivel"};
        //Establece el nombre a las columnas. Se le debe pasar un object[]
        dtm.setColumnIdentifiers(columnas);
            
        // NUEVO !!
        //3- Añado la lista de clientes que tenga en la lógica de negocio
        //Recupero lista clientes
        List<Hijo> listaHijos = Logica.getListaHijos();
        //La recorro y la voy añadiendo a la tabla
        for(Hijo hijo: listaHijos){
            dtm.addRow(hijo.toArrayString());
        }//end foreach
        
            
        //4- Establecer el modelo para el componente JTable        
        this.tblHijos.setModel(dtm); 
        
        //5- Hacemos que la tabla NO sea modificable
        this.tblHijos.setEnabled(false);
        //Si no lo hacemos los datos de ALTA de la tabla podrán ser modificcados
        mostrarTabla();
    }//end inicializarTabla

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpTurno = new javax.swing.ButtonGroup();
        panelGeneral = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        panelInterno = new javax.swing.JPanel();
        lbDeporte = new javax.swing.JLabel();
        inputDeporte = new javax.swing.JComboBox<>();
        lbNivel = new javax.swing.JLabel();
        inputNivel = new javax.swing.JSpinner();
        lbTurno = new javax.swing.JLabel();
        inputManana = new javax.swing.JRadioButton();
        inputTarde = new javax.swing.JRadioButton();
        lbRenovacion = new javax.swing.JLabel();
        inputTrimestral = new javax.swing.JCheckBox();
        inputAnual = new javax.swing.JCheckBox();
        separador = new javax.swing.JSeparator();
        panelHijos = new javax.swing.JPanel();
        btnToggleTabla = new javax.swing.JButton();
        btnAddHijo = new javax.swing.JButton();
        scrollTblHijos = new javax.swing.JScrollPane();
        tblHijos = new javax.swing.JTable();
        btnMatricular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("REGISTRO DEPORTIVO");

        panelInterno.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Seleccion deporte", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        panelInterno.setPreferredSize(new java.awt.Dimension(419, 128));

        lbDeporte.setText("Deporte");

        inputDeporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tenis", "Padel", "Squash" }));

        lbNivel.setText("Nivel");

        inputNivel.setModel(new javax.swing.SpinnerListModel(new String[] {"Inicial", "Medio", "Avanzado", "Profesional"}));

        lbTurno.setText("Turno");

        btnGrpTurno.add(inputManana);
        inputManana.setText("Mañana");

        btnGrpTurno.add(inputTarde);
        inputTarde.setText("Tarde");

        lbRenovacion.setText("Renovacion");

        inputTrimestral.setText("Trimestral");

        inputAnual.setText("Anual");

        panelHijos.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Hijos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        panelHijos.setPreferredSize(new java.awt.Dimension(397, 65));
        panelHijos.setRequestFocusEnabled(false);

        btnToggleTabla.setLabel("Ver/Ocultar tabla");
        btnToggleTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToggleTablaActionPerformed(evt);
            }
        });

        btnAddHijo.setLabel("Añadir HIjo");
        btnAddHijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHijoActionPerformed(evt);
            }
        });

        tblHijos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollTblHijos.setViewportView(tblHijos);

        javax.swing.GroupLayout panelHijosLayout = new javax.swing.GroupLayout(panelHijos);
        panelHijos.setLayout(panelHijosLayout);
        panelHijosLayout.setHorizontalGroup(
            panelHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHijosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnToggleTabla)
                .addGap(146, 146, 146)
                .addComponent(btnAddHijo)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHijosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTblHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelHijosLayout.setVerticalGroup(
            panelHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHijosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnToggleTabla)
                    .addComponent(btnAddHijo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTblHijos, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelInternoLayout = new javax.swing.GroupLayout(panelInterno);
        panelInterno.setLayout(panelInternoLayout);
        panelInternoLayout.setHorizontalGroup(
            panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoLayout.createSequentialGroup()
                .addGroup(panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelInternoLayout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(lbNivel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInternoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelInternoLayout.createSequentialGroup()
                                .addComponent(lbDeporte, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(inputManana, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputTarde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTurno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(90, 90, 90)
                        .addGroup(panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputTrimestral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputAnual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbRenovacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelInternoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(separador)
                .addContainerGap())
            .addComponent(panelHijos, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );
        panelInternoLayout.setVerticalGroup(
            panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDeporte)
                    .addComponent(lbNivel)
                    .addComponent(inputNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTurno)
                    .addComponent(lbRenovacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputManana)
                    .addComponent(inputTrimestral))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTarde)
                    .addComponent(inputAnual))
                .addGap(18, 18, 18)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelHijos, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnMatricular.setLabel("MATRICULAR");
        btnMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMatricular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInterno, javax.swing.GroupLayout.Alignment.LEADING, 421, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInterno, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMatricular)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnToggleTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToggleTablaActionPerformed
        boolean esVisible = this.scrollTblHijos.isVisible();
        if (esVisible) {
            ocultarTabla();
        } else {
            mostrarTabla();
        }
    }//GEN-LAST:event_btnToggleTablaActionPerformed

    private void btnAddHijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHijoActionPerformed
                //Creación dialogo de alta y lo mostramos
        D_AddHijo dHijo = new D_AddHijo (this,true);
        dHijo.setLocationRelativeTo(null);//Centrar el JDialog al cargar
        dHijo.setVisible(true);
        //actualizar tabla
        refrescarTabla();
    }//GEN-LAST:event_btnAddHijoActionPerformed

    private void btnMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularActionPerformed
        //recoger datos
        //validacion
        
    }//GEN-LAST:event_btnMatricularActionPerformed

    private void ocultarTabla() {
        //check si es necesario ocultar
        this.scrollTblHijos.setVisible(false);
        this.tblHijos.setVisible(false);
        this.pack();
    }

    private void mostrarTabla() {
        //check si es necesario mostrar
        this.scrollTblHijos.setVisible(true);
        this.tblHijos.setVisible(true);
        this.pack();
    }
    private void mostrarError(String msg) {
        D_Error dError = new D_Error(this, true, msg);
        dError.setLocationRelativeTo(this);
        dError.setVisible(true);
    }
        private void mostrarExito(String msg) {
        D_Exito dExito = new D_Exito(this, true, msg);
        dExito.setLocationRelativeTo(this);
        dExito.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddHijo;
    private javax.swing.ButtonGroup btnGrpTurno;
    private javax.swing.JButton btnMatricular;
    private javax.swing.JButton btnToggleTabla;
    private javax.swing.JCheckBox inputAnual;
    private javax.swing.JComboBox<String> inputDeporte;
    private javax.swing.JRadioButton inputManana;
    private javax.swing.JSpinner inputNivel;
    private javax.swing.JRadioButton inputTarde;
    private javax.swing.JCheckBox inputTrimestral;
    private javax.swing.JLabel lbDeporte;
    private javax.swing.JLabel lbNivel;
    private javax.swing.JLabel lbRenovacion;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTurno;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel panelHijos;
    private javax.swing.JPanel panelInterno;
    private javax.swing.JScrollPane scrollTblHijos;
    private javax.swing.JSeparator separador;
    private javax.swing.JTable tblHijos;
    // End of variables declaration//GEN-END:variables

}
